Numpy: Numerical Python

In [1]:
import numpy as np
import pandas as pd
import time


In [3]:
ruta = "C:/Users/hherre13/OneDrive - JNJ/Documents/Hector/Python Total para data science/Día 8/Cuadernos para Prácticas/Ciudades_Visitadas_Latinoamerica_2023.csv"
df =pd.read_csv(ruta)
df

Ciudad       País  Población  Visitantes
0   Ciudad de México     México    9265833    21000000
1       Buenos Aires  Argentina    3059574    15000000
2     Río de Janeiro     Brasil    6748314    13000000
3               Lima       Perú    9756020     9000000
4             Bogotá   Colombia    7181663     8000000
5  Santiago de Chile      Chile    6199241     7500000
6          São Paulo     Brasil   12333146    20000000
7          La Habana       Cuba    2164182     4000000
8             Cancún     México     888124     5000000
9          Cartagena   Colombia    1036671     3000000

In [7]:
#Mean
np.round(df["Población"].mean())

5863277.0

In [8]:
np.min(df["Visitantes"])

3000000

In [10]:
#Ejercicio

import pandas as pd 
import numpy as np 


datos = {
    "Ciudad": ["Ciudad de México", "Buenos Aires", "Río de Janeiro", "Lima", "Bogotá", "Santiago de Chile", "São Paulo", "La Habana", "Cancún", "Cartagena"],
    "País": ["México", "Argentina", "Brasil", "Perú", "Colombia", "Chile", "Brasil", "Cuba", "México", "Colombia"],
    "Población": [9265833, 3059574, 6748314, 9756020, 7181663, 6199241, 12333146, 2164182, 888124, 1036671],
    "Visitantes": [21000000, 15000000, 13000000, 9000000, 8000000, 7500000, 20000000, 4000000, 5000000, 3000000]
}

df = pd.DataFrame(datos)

promedio_poblacion = np.round(df["Población"].mean())
promedio_poblacion

5863277.0

In [11]:
#Ejercicio 2 

import pandas as pd 
import numpy as np 

datos = {
    "Ciudad": ["Ciudad de México", "Buenos Aires", "Río de Janeiro", "Lima", "Bogotá", "Santiago de Chile", "São Paulo", "La Habana", "Cancún", "Cartagena"],
    "País": ["México", "Argentina", "Brasil", "Perú", "Colombia", "Chile", "Brasil", "Cuba", "México", "Colombia"],
    "Población": [9265833, 3059574, 6748314, 9756020, 7181663, 6199241, 12333146, 2164182, 888124, 1036671],
    "Visitantes": [21000000, 15000000, 13000000, 9000000, 8000000, 7500000, 20000000, 4000000, 5000000, 3000000]
}

df = pd.DataFrame(datos)

min_visitantes  =np.min(df["Visitantes"])
min_visitantes


3000000

In [12]:
#Ejercicio 3


import pandas as pd 
import numpy as np 

datos = {
    "Ciudad": ["Ciudad de México", "Buenos Aires", "Río de Janeiro", "Lima", "Bogotá", "Santiago de Chile", "São Paulo", "La Habana", "Cancún", "Cartagena"],
    "País": ["México", "Argentina", "Brasil", "Perú", "Colombia", "Chile", "Brasil", "Cuba", "México", "Colombia"],
    "Población": [9265833, 3059574, 6748314, 9756020, 7181663, 6199241, 12333146, 2164182, 888124, 1036671],
    "Visitantes": [21000000, 15000000, 13000000, 9000000, 8000000, 7500000, 20000000, 4000000, 5000000, 3000000]
}

df = pd.DataFrame(datos)

max_visitantes  =np.max(df["Visitantes"])
max_visitantes


21000000

Arrays

In [13]:
mi_array = np.array([1,2,3,4,5])
mi_array

array([1, 2, 3, 4, 5])

In [14]:
type(mi_array)

numpy.ndarray

In [15]:
#Comparacion velocidad
lista_grande = list(range(1000000))
array_grande=np.array(lista_grande)

In [16]:
type(lista_grande)

list

In [17]:
type(array_grande)

numpy.ndarray

In [19]:
import time

inicio_lista = time.time()
for i in lista_grande:
    i**2
fin_lista =time.time()
print("Tiempo lista: ",fin_lista-inicio_lista)

Tiempo lista:  0.050078392028808594


In [20]:
inicio_lista = time.time()
array_grande **2
fin_lista =time.time()
print("Tiempo lista: ",fin_lista-inicio_lista)

Tiempo lista:  0.002464771270751953


Arrays

In [1]:
import numpy as np
array = np.array([1,2,3])

In [2]:
len(array)

3

In [3]:
array.shape

(3,)

In [6]:
array_2d = np.array([[1,2,3],[4,5,6]])
array_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
len(array_2d)

2

In [8]:
array_2d.shape

(2, 3)

In [10]:
import numpy as np

array_enteros = np.array([1,2,3,4,5,6,7,8,9,10])
form_array = array_enteros.shape
print(form_array)

(10,)


Manipular arrays

In [11]:
x = [1,2,3]
y = [1,2,3]
z = [1,2,3]


In [12]:
np.concatenate([x,y,z])

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [13]:
a = [[1,2],
    [3,4]]
b = [[5,6],
    [7,8]]

np.concatenate([a,b],axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [14]:
a = [[1,2],
    [3,4]]
b = [[5,6],
    [7,8]]

np.concatenate([a,b],axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [15]:
array_concatenado = np.concatenate([a,b],axis=0)

In [18]:
array_concatenado.shape

(4, 2)

In [19]:
array_reformado  = array_concatenado.reshape(2,4)
array_reformado

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [20]:
array_sumado = array_reformado + array_reformado
array_sumado

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16]])

In [21]:
array_multi = array_reformado * array_reformado
array_multi

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [24]:
raices = np.sqrt(array_multi)
raices

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

Indexacion y Segmentacion

In [2]:
import numpy as np

array1d = np.array([1,2,3,4,5])
array2d= np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])

In [3]:
array1d [0]

1

In [4]:
array1d[-1]

5

In [5]:
array2d[0] ##Me brinda el primer elemento de la lisa grande [[1,2,3],[4,5,6]]

array([1, 2, 3])

In [6]:
#quiero el 6
array2d[1][2]

6

In [7]:
#quiero el 2
array2d[0][1] #primero la fila y luego el indice dentro de la fila

2

In [8]:
array2d[1,2] #Se puede hacer de esta fomra

6

In [9]:
#Slicing
array1d[1:4]

array([2, 3, 4])

In [10]:
array2d[1, :] ##Arranco con la fila 1 y luego quiero toda la fila

array([4, 5, 6])

In [11]:
#los dos ultimos numoers
array2d[1, 1:3]

array([5, 6])

In [12]:
#Columna completa
array2d[:,1] #Todo y luego la primer columna

array([2, 5, 8])

In [14]:
array2d[:2,:2] #Las primeras dos columnas hsata la segunda fila

array([[1, 2],
       [4, 5]])

In [15]:
#Numeros mayores a 3
array1d > 3

array([False, False, False,  True,  True])

In [16]:
array2d%2 == 0 

array([[False,  True, False],
       [ True, False,  True],
       [False,  True, False]])

Forma y estructura 

In [25]:
array= np.array([1,2,3,4,5,6,7,8,9])

In [26]:
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
array.shape

(9,)

In [28]:
array_mod = array.reshape(3,3)
array_mod

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
array_mod2=array.reshape(-1,3)
array_mod2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
array_volteado = array_mod2.transpose()

In [32]:
array_volteado

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [33]:
array_chato = array_mod.flatten()

In [34]:
array_chato

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
array_ravel = array_mod.ravel()

In [36]:
array_ravel 

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
import numpy as np
#Array siempre del mismo tipo

ruta = "C:\\Users\\hherre13\\OneDrive - JNJ\\Documents\\Hector\\Python Total para data science\\Día 8\\Cuadernos para Prácticas\\medallas.csv"

In [3]:
array = np.genfromtxt(ruta)

ValueError: Some errors were detected !
    Line #15 (got 2 columns instead of 1)
    Line #17 (got 2 columns instead of 1)
    Line #20 (got 2 columns instead of 1)
    Line #22 (got 2 columns instead of 1)
    Line #24 (got 2 columns instead of 1)
    Line #27 (got 4 columns instead of 1)
    Line #36 (got 2 columns instead of 1)
    Line #39 (got 3 columns instead of 1)
    Line #44 (got 4 columns instead of 1)
    Line #63 (got 2 columns instead of 1)
    Line #65 (got 2 columns instead of 1)
    Line #70 (got 2 columns instead of 1)
    Line #72 (got 3 columns instead of 1)
    Line #73 (got 3 columns instead of 1)
    Line #74 (got 4 columns instead of 1)
    Line #77 (got 2 columns instead of 1)
    Line #78 (got 2 columns instead of 1)
    Line #82 (got 2 columns instead of 1)
    Line #86 (got 3 columns instead of 1)

In [6]:
array = np.genfromtxt(ruta,delimiter=",")
array

array([[ nan,  nan,  nan,  nan,  nan],
       [ nan,   1.,   2.,   3.,  nan],
       [ nan,   2.,   2.,   4.,  nan],
       [ 17.,   7.,  22.,  46.,  nan],
       [  1.,   1.,   5.,   7.,  nan],
       [ nan,   3.,   4.,   7.,  nan],
       [  2.,  nan,  nan,   2.,  nan],
       [ nan,   1.,  nan,   1.,  nan],
       [  1.,   3.,   3.,   7.,  nan],
       [  3.,   1.,   3.,   7.,  nan],
       [  1.,  nan,  nan,   1.,  nan],
       [ nan,  nan,   1.,   1.,  nan],
       [  7.,   6.,   8.,  21.,  nan],
       [  3.,   1.,   2.,   6.,  nan],
       [ nan,  nan,   1.,   1.,  nan],
       [  7.,   6.,  11.,  24.,  nan],
       [  2.,   4.,   6.,  12.,  nan],
       [ nan,   4.,   1.,   5.,  nan],
       [  3.,   3.,   2.,   8.,  nan],
       [ nan,  nan,   1.,   1.,  nan],
       [  7.,   3.,   5.,  15.,  nan],
       [  4.,   4.,   3.,  11.,  nan],
       [  3.,   4.,   4.,  11.,  nan],
       [ nan,   3.,   2.,   5.,  nan],
       [  2.,   1.,  nan,   3.,  nan],
       [  1.,   1.,   4.,

In [7]:
array = np.genfromtxt(ruta,delimiter=",", filling_values = 0)
array

array([[  0.,   0.,   0.,   0.,   0.],
       [  0.,   1.,   2.,   3.,   0.],
       [  0.,   2.,   2.,   4.,   0.],
       [ 17.,   7.,  22.,  46.,   0.],
       [  1.,   1.,   5.,   7.,   0.],
       [  0.,   3.,   4.,   7.,   0.],
       [  2.,   0.,   0.,   2.,   0.],
       [  0.,   1.,   0.,   1.,   0.],
       [  1.,   3.,   3.,   7.,   0.],
       [  3.,   1.,   3.,   7.,   0.],
       [  1.,   0.,   0.,   1.,   0.],
       [  0.,   0.,   1.,   1.,   0.],
       [  7.,   6.,   8.,  21.,   0.],
       [  3.,   1.,   2.,   6.,   0.],
       [  0.,   0.,   1.,   1.,   0.],
       [  7.,   6.,  11.,  24.,   0.],
       [  2.,   4.,   6.,  12.,   0.],
       [  0.,   4.,   1.,   5.,   0.],
       [  3.,   3.,   2.,   8.,   0.],
       [  0.,   0.,   1.,   1.,   0.],
       [  7.,   3.,   5.,  15.,   0.],
       [  4.,   4.,   3.,  11.,   0.],
       [  3.,   4.,   4.,  11.,   0.],
       [  0.,   3.,   2.,   5.,   0.],
       [  2.,   1.,   0.,   3.,   0.],
       [  1.,   1.,   4.,

In [9]:
array = np.genfromtxt(ruta,delimiter=",", filling_values = 0, skip_header = 1)
array

array([[  0.,   1.,   2.,   3.,   0.],
       [  0.,   2.,   2.,   4.,   0.],
       [ 17.,   7.,  22.,  46.,   0.],
       [  1.,   1.,   5.,   7.,   0.],
       [  0.,   3.,   4.,   7.,   0.],
       [  2.,   0.,   0.,   2.,   0.],
       [  0.,   1.,   0.,   1.,   0.],
       [  1.,   3.,   3.,   7.,   0.],
       [  3.,   1.,   3.,   7.,   0.],
       [  1.,   0.,   0.,   1.,   0.],
       [  0.,   0.,   1.,   1.,   0.],
       [  7.,   6.,   8.,  21.,   0.],
       [  3.,   1.,   2.,   6.,   0.],
       [  0.,   0.,   1.,   1.,   0.],
       [  7.,   6.,  11.,  24.,   0.],
       [  2.,   4.,   6.,  12.,   0.],
       [  0.,   4.,   1.,   5.,   0.],
       [  3.,   3.,   2.,   8.,   0.],
       [  0.,   0.,   1.,   1.,   0.],
       [  7.,   3.,   5.,  15.,   0.],
       [  4.,   4.,   3.,  11.,   0.],
       [  3.,   4.,   4.,  11.,   0.],
       [  0.,   3.,   2.,   5.,   0.],
       [  2.,   1.,   0.,   3.,   0.],
       [  1.,   1.,   4.,   6.,   0.],
       [ 39.,  41.,  33.,

In [10]:
array = np.genfromtxt(ruta,delimiter=",", filling_values = 0, skip_header = 1,dtype = int)
array

array([[  0,   1,   2,   3,   0],
       [  0,   2,   2,   4,   0],
       [ 17,   7,  22,  46,   0],
       [  1,   1,   5,   7,   0],
       [  0,   3,   4,   7,   0],
       [  2,   0,   0,   2,   0],
       [  0,   1,   0,   1,   0],
       [  1,   3,   3,   7,   0],
       [  3,   1,   3,   7,   0],
       [  1,   0,   0,   1,   0],
       [  0,   0,   1,   1,   0],
       [  7,   6,   8,  21,   0],
       [  3,   1,   2,   6,   0],
       [  0,   0,   1,   1,   0],
       [  7,   6,  11,  24,   0],
       [  2,   4,   6,  12,   0],
       [  0,   4,   1,   5,   0],
       [  3,   3,   2,   8,   0],
       [  0,   0,   1,   1,   0],
       [  7,   3,   5,  15,   0],
       [  4,   4,   3,  11,   0],
       [  3,   4,   4,  11,   0],
       [  0,   3,   2,   5,   0],
       [  2,   1,   0,   3,   0],
       [  1,   1,   4,   6,   0],
       [ 39,  41,  33, 113,   0],
       [  1,   0,   1,   2,   0],
       [  1,   1,   2,   4,   0],
       [  1,   0,   1,   2,   0],
       [  0,  

In [11]:
array_ejmplo = np.array([[1,2,4],
                        [4,5,6]])

In [12]:
#Saving

ruta = "C:\\Users\\hherre13\\OneDrive - JNJ\\Documents\\Hector\\Python Total para data science\\Día 8\\Cuadernos para Prácticas\\myarray.csv"

In [14]:
np.savetxt(ruta, array_ejmplo, delimiter = ",",fmt = "%d")

Integracion pandas y Numpy

In [15]:
import numpy as np
import pandas as pd

df = pd.DataFrame({
    "Impares":[1,3,5],
    "Pares": [2,4,6]
})

df

Impares  Pares
0        1      2
1        3      4
2        5      6

In [17]:
array_n1 =df.values
array_n1

array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int64)

In [19]:
array_n2 = df.to_numpy()
array_n2

array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int64)

In [20]:
np.sqrt(df)

Impares     Pares
0  1.000000  1.414214
1  1.732051  2.000000
2  2.236068  2.449490

In [24]:
df_desde_np = pd.DataFrame(array_n1,columns=["Col1","Col2"])
df_desde_np

Col1  Col2
0     1     2
1     3     4
2     5     6

In [39]:
#Ejercicio 1

import numpy as np 
import pandas as pd 

mi_dataframe = pd.DataFrame({"Frutas":["Manzana","Banana","Cereza"],
                            "Cantidad":[5,8,3]})


array_frutas = mi_dataframe.values
array_frutas

array([['Manzana', 5],
       ['Banana', 8],
       ['Cereza', 3]], dtype=object)

In [42]:
#Ejercicio 2 
import pandas as pd 
import numpy as np 

mi_dataframe = pd.DataFrame({"Frutas":["Manzana","Banana","Cereza"],
                            "Cantidad":[5,8,3]})

mi_dataframe_filtrado = mi_dataframe[mi_dataframe["Cantidad"] > 4]

array_filtrado = mi_dataframe_filtrado.values
array_filtrado

array([['Manzana', 5],
       ['Banana', 8]], dtype=object)

In [ ]:
#Ejercicio 3

import numpy as np
import pandas as pd

# Crear el array de NumPy
mi_array = np.array([[10, 40], [20, 50], [30, 60]])

# Convertir el array en un DataFrame de Pandas
df_numeros = pd.DataFrame(mi_array, columns=['Decenas', 'Centenas'])

# Mostrar el DataFrame
print(df_numeros)
